### ISSUE TITLE
awless show error

### ISSUE THREAD

**Issue by hectorv** [wallix/awless#161] opened 2017-11-04 20:03 UTC
I keep getting errors for different calls to `awless show`:

```
❯ awless show i-1b169f9c
[error]   file '/Users/hector/.awless/aws/rdf/us-east-1/infra.triples': tok ' .
<vol-14212bbc> <cloud:type> "gp2':reaching literate but missing element (node count 0)

❯ awless show AIDAIJYONYZNJAECNQ4FY
[error]   file '/Users/hector/.awless/aws/rdf/us-east-1/infra.triples': tok ' .
<vol-14212bbc> <cloud:type> "gp2':reaching literate but missing element (node count 0)
```

```
❯ awless --version
awless version=v0.1.5, commit=21a3a94174dfe7033ce760f050c187637100d22e, build-date=2017-10-05T14:56:19+02:00, build-arch=amd64, build-os=darwin, build-for=targz
```

Any ideas what could be wrong? Thanks!

**Comment by simcap** [comment] 2017-11-05 09:56
Thanks for reporting @hectorv , quite a key issue.

_Explanations_: `awless` encode locally the cloud data using the RDF format. We use [triplestore](https://github.com/wallix/triplestore) for encode/decode store. Here the store tells us it cannot decode the data line concerning the volume (this is the NTriple RDF encoding format we use). It could be due to an escape characters or an shortcoming in our triplestore codec.

To fix it, we will need to see what the triplestore cannot parse, so basically get the full line causing the codec issue. 

So here are the steps for you at the command line:

1. run a command to reproduce the error (to make sure it is still there and has not been overwritten by a sync)
2. do not run any other `awless` command
3. do a grep on the file in error grabbing the line in error with some context line around. Ex: `grep -C "<vol-14212bbc> <cloud:type>" /Users/hector/.awless/aws/rdf/us-east-1/infra.triples ` (note that if you just put the volume id here you will get to many lines so by adding more char to grep we get a unique line)
4. put the output of the grep in this issue.

(The grep command will output the line in error with 2 lines above and below so we can see the multi-line context i.e. linefeed, carriage returns, etc...).

Then I will work on it starting Tuesday!

**Comment by hectorv** [comment] 2017-11-06 22:08
@simcap thanks for the detailed instructions :)
Here it is:

```
<arn:aws:ecs:us-east-1:xxx:container-instance/77879497-e51c-43e8-ad2c-0cd9d62dc7fe> <cloud:attributes> <831ce0f2> .
<ami-e22c518b> <cloud:description> "differs from api-server.1.0_x64 (ami-1dbec974) in that it it includes some image libraries and pillow.  This box is really small, but the exact commands are documented in an email between Alice and Bob entitled "Installing pillow on the webservers"." .
<vol-14212bbc> <cloud:type> "gp2" .
<i-0265ac85d85050421> <cloud:vpc> <vpc-ed1b1d84> .
<arn:aws:ecr:us-east-1:xxx:repository/quiz-web-prod> <cloud:account> "xxx" .
```

**Comment by simcap** [comment] 2017-11-07 09:34
The issue is our [NTriple parser](https://github.com/wallix/triplestore/blob/master/ntparser.go) parsing the line:

```
<ami-e22c518b> <cloud:description> "differs from api-server.1.0_x64 (ami-1dbec974) in that it it includes some image libraries and pillow.  This box is really small, but the exact commands are documented in an email between Alice and Bob entitled "Installing pillow on the webservers"." .
```

We can reduce this line - while still exposing the error - to:

```
<node> <node> "anystring ""." .
```

The lenient parser currently uses `".` or `" .` as a terminator of a  NTriple of the form  *subject, predicate, string literal*. Here a terminator token appears before the real end one. So the parsing of the next triple begins earlier making the next line (with the volume) faulty.

The parser implementation has been done this way for various reason. But obviously this is a limitation that we need to improve on.

@hectorv While we are fixing the issue, in the meantime you can solve the issue if you edit the description string (through the web console) of the AMI (if this is not an official one) to use single quote instead of double, or to remove the dot `.` at the end.

If you cannot edit that string or if that does not make sense let me know.

**Comment by hectorv** [comment] 2017-11-07 13:36
@simcap thanks, editing the AMI description did the trick.
I also had to force a re-sync (maybe there's a better way):
```
❯ rm -fr ~/.awless
```

**Comment by simcap** [comment] 2017-11-07 13:59
Good! 

Other easier way to re-sync would be:

```
$ awless sync -r my-correct-region

or only the infra as we know it is the volume who is concerned

$ awless sync --infra -r my-region
```

We will  close this issue once it is properly fixed. Thanks.

**Comment by simcap** [comment] 2018-01-08 13:56
Closed with [fix in wallix/triplestore dependency](https://github.com/wallix/triplestore/commit/461130b4b99a2dd36f78000abf208bfcce46b07d)

**Closed by simcap** 2018-01-08 13:56 UTC
Labels: bug
