### ISSUE TITLE
awless list loadbalancers output is null, but awscli not.

### ISSUE THREAD

**Issue by Niemi** [wallix/awless#138] opened 2017-08-29 13:58 UTC
Hi to all,
maybe i type something wrong, but others command works as expected.
Thanks you,
``
[AWLESS]
aleksei@ic450ak:~/awlessNEW$ ./awless --version
awless version=v0.1.1, commit=e4981514f29034deaf6466aff60b9909a0e7810a, build-date=2017-07-11T10:56:40+02:00, build-arch=amd64, build-os=linux, build-for=zip
aleksei@ic450ak:~/awlessNEW$ ./awless -p STAGE list  loadbalancers 
No results found.
aleksei@ic450ak:~/awlessNEW$ awless --version
awless version=v0.1.2, commit=eba3785ddc894b116cf0762e1759c26c459f8077, build-date=2017-08-17T11:20:20+02:00, build-arch=amd64, build-os=linux, build-for=targz
aleksei@ic450ak:~/awlessNEW$ awless -p STAGE list loadbalancers 
No results found.
[AWS cli]
leksei@ic450ak:~/awlessNEW$ aws  --version 
aws-cli/1.11.13 Python/3.5.2 Linux/4.4.0-92-generic botocore/1.4.70
aleksei@ic450ak:~/awlessNEW$ aws --profile STAGE --region eu-west-1 elb describe-load-balancers  --output text --max-items 1|tail -n1
NEXTTOKEN	eyJi***************DEsICJNYXJrZXIiOiBudWxsfQ==
(output changed)
``

**Comment by fxaguessy** [comment] 2017-08-29 14:22
Duplicate of #103 and #71, for now, `awless list loadbalancers` only lists [elbv2 (application)](http://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html) loadbalancers

**Closed** 2017-08-29 14:22 UTC
Labels: duplicate
