### ISSUE TITLE
awsless and MFA

### ISSUE THREAD

**Issue by versus** [wallix/awless#125] opened 2017-07-24 14:44 UTC
I’m using a multi-factor authentication device (MFA), but when i use awsless i need enter new code everytime. It is very slowing my work. Can you add cache of token for your awesome tool?

**Comment by fxaguessy** [comment] 2017-07-24 14:51
Duplicate of #109.
This has been added on `master` (`go get -u github.com/wallix/awless`) and will be in next release: `v0.1.2`

**Closed by fxaguessy** 2017-07-24 14:52 UTC
