### ISSUE TITLE
awless ssh INSTANCE seems broken in 0.0.24

### ISSUE THREAD

**Issue by sdouche** [wallix/awless#100] opened 2017-05-22 13:01 UTC
With the last version (0.0.24), I can't connect to the instance:
```
$ awless -p sr-sandbox list instances
|        ID ▲         |    ZONE    | NAME |  STATE  |   TYPE   |   PUBLIC IP    |  PRIVATE IP   |  UPTIME  |       KEYPAIR       |
|---------------------|------------|------|---------|----------|----------------|---------------|----------|---------------------|
| i-00c5a341da308a8e4 | eu-west-1b | test | running | t2.micro | 34.248.157.00  | 172.31.15.107 | 15 hours | aws-sr-sandbox-test |
| i-046a2755623e43ebe | eu-west-1b | test | running | t2.micro | 52.213.140.00  | 172.31.14.85  | 15 hours | aws-sr-sandbox-test |
| i-0a0049b6241b2eeba | eu-west-1b | test | running | t2.micro | 52.49.150.00   | 172.31.12.80  | 2 days   | aws-sr-sandbox-test |
| i-0bc587b1ce4304b3a | eu-west-1b | test | running | t2.micro | 52.208.219.000 | 172.31.4.5    | 15 hours | aws-sr-sandbox-test |

$ awless -p sr-sandbox ssh i-00c5a341da308a8e4
[warning] port 22 is not open on this instance
Error: instance not accessible
````

No issue with the version 0.0.23:
 ```
$ awless-0.0.23  --aws-profile sr-sandbox list instances
|        ID ▲         |    ZONE    | NAME |  STATE  |   TYPE   |   PUBLIC IP    |  PRIVATE IP   |  UPTIME  |       KEYPAIR       |
|---------------------|------------|------|---------|----------|----------------|---------------|----------|---------------------|
| i-00c5a341da308a8e4 | eu-west-1b | test | running | t2.micro | 34.248.157.00  | 172.31.15.107 | 15 hours | aws-sr-sandbox-test |
| i-046a2755623e43ebe | eu-west-1b | test | running | t2.micro | 52.213.140.00  | 172.31.14.85  | 15 hours | aws-sr-sandbox-test |
| i-0a0049b6241b2eeba | eu-west-1b | test | running | t2.micro | 52.49.150.00   | 172.31.12.80  | 2 days   | aws-sr-sandbox-test |
| i-0bc587b1ce4304b3a | eu-west-1b | test | running | t2.micro | 52.208.219.000 | 172.31.4.5    | 15 hours | aws-sr-sandbox-test |

awless-0.0.23 --aws-profile sr-sandbox ssh i-00c5a341da308a8e4
[info]    Login as 'ubuntu' on '34.248.157.00', using keypair '/home/sdouche/.awless/keys/xxx.pem' with ssh client at '/usr/bin/ssh'
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-1013-aws x86_64)
```

**Comment by fxaguessy** [comment] 2017-05-22 13:08
Could you try with the `-e` (i.e. --extra-verbose) flag ?

**Comment by simcap** [comment] 2017-05-22 14:12
I might have introduced a regression when refactoring SSH between 0.0.23/0.0.24. I thought I tested all cases by hand (since SSH does not play nice with unit tests and our smoke tests do not capture this SSH use case in particular).

I will reproduce it and fix it.

@sdouche any particular settings I should be aware about: accessing from within a VPC, SSH port different that default 22, etc ... Anyway we can see that you just upgraded and it does not work anymore, so I am on it!

**Comment by simcap** [comment] 2017-05-22 14:14
@sdouche Also , a `awless show` of the security group applied on the instance might help understand the issue.

You can first do a `awless show i-00c5a341da308a8e4`, get the ID of the security group showing for the instance and do a `awless show {ID_OF_SEC_GROUP}`.

Thanks.

**Comment by simcap** [comment] 2017-05-22 15:25
(Oups closed it by accident with my commit. I leave it open since it is half resolved in my view)

**Comment by sdouche** [comment] 2017-05-22 16:22
@simcap It's a vanilla account for testing (default VPC, default networks) with only authorized IP addresses to connect (firewall).

With extra-verbose:
```
awless -p sr-sandbox -e ssh i-00c5a341da308a8e4
[verbose] loading AWS session with profile 'sr-sandbox' and region 'eu-west-1'
[verbose] trying with user ec2-user
[verbose] trying with user ubuntu
[warning] port 22 is not open on this instance
Error: instance not accessible
```
It works with master:
```
$ go get -u github.com/wallix/awless
$ ~/src/go/bin/awless -p sr-sandbox -e ssh i-00c5a341da308a8e4
[verbose] loading AWS session with profile 'sr-sandbox' and region 'eu-west-1'
[verbose] trying with user ec2-user
[verbose] trying with user ubuntu
[info]    Login as 'ubuntu' on '34.248.157.80', using keypair '/home/sdouche/.awless/keys/aws-sr-sandbox-test.pem' with ssh client '/usr/bin/ssh'

Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-1013-aws x86_64)
```

**Comment by simcap** [comment] 2017-05-23 08:42
@sdouche Thanks! There will be a 0.0.25 soon with that fix.

I fear there is another bug lurking in there (ex: port range definition against AWS, security group notation, etc ...).

It would be great if you could `awless show` the security group applying on that instance. Here are the steps:
* `awless show i-00c5a341da308a8e4` (_synchronize what is needed and show instance in detail as well as security groups applying to it_)
* `awless show {securitygroup_id_or_name_from_above}`

And then dump in this issue all the info (obfuscating IPs if you need, but not the ports ;) ). Cheers!

**Comment by sdouche** [comment] 2017-05-23 11:28
```
$ ~/src/go/bin/awless -p sr-sandbox show i-00c5a341da308a8e4
[info]    cannot resolve resource - running full sync
|    PROPERTY ▲     |                                         VALUE                                          |
|-------------------|----------------------------------------------------------------------------------------|
| Architecture      | x86_64                                                                                 |
| Hypervisor        | xen                                                                                    |
| ID                | i-00c5a341da308a8e4                                                                    |
| Image             | ami-a8d2d7ce                                                                           |
| KeyPair           | aws-sr-sandbox-test                                                                    |
| Name              | test                                                                                   |
| NetworkInterfaces | [eni-7085795b]                                                                         |
| Private IP        | 172.31.15.107                                                                          |
| Public IP         | 34.248.157.80                                                                          |
| PublicDNS         | ec2-34-248-157-80.eu-west-1.compute.amazonaws.com                                      |
| RootDevice        | /dev/sda1                                                                              |
| RootDeviceType    | ebs                                                                                    |
| SecurityGroups    | [sg-281e8651]                                                                          |
| State             | running                                                                                |
| Subnet            | subnet-7abe4a1d                                                                        |
| Tags              | [Environment=test Name=test Role=test Owner=sdouche Service=sysadmin Application=test] |
| Type              | t2.micro                                                                               |
| Uptime            | 37 hours                                                                               |
| Vpc               | vpc-3f9f7758                                                                           |
| Zone              | eu-west-1b                                                                             |

# Relations:
eu-west-1[region]
	↳ vpc-3f9f7758[vpc]
		↳ subnet-7abe4a1d[subnet]
			↳ @test[instance]

Depending on: aws-sr-sandbox-test[keypair], @all-sr[securitygroup], vol-07f9e2786d71aae89[volume]

Siblings: @test[instance], @test[instance], @test[instance], ... (display all with flag --siblings)


~/src/go/bin/awless -p sr-sandbox show sg-281e8651                                                                       1832ms
| PROPERTY ▲  |          VALUE          |
|-------------|-------------------------|
| Description | All with SR             |
| ID          | sg-281e8651             |
| Inbound     | [0.0.0.0/0](tcp:65535)  |
| Name        | all-sr                  |
| Outbound    | [0.0.0.0/0](any)        |
| Owner       | 926110281705            |
| Tags        | [Name=all-sr]           |
| Vpc         | vpc-3f9f7758            |

# Relations:
eu-west-1[region]
	↳ vpc-3f9f7758[vpc]
		↳ @all-sr[securitygroup]

Applied on: @test[instance], @test[instance], @test[instance], @test[instance], @test[instance], @test[instance], @test[instance]

Siblings: @default[securitygroup]

```

**Comment by simcap** [comment] 2017-05-24 13:38
Fixed (i.e. now able to login despite warning) in master and upcoming releases. 

Note the root cause causing the display of `[warning] port 22 is not open on this instance` (and still be able to login) is not reproducible on our side.

bd6f12a commit has been added to display an error that was swallowed (!) so that in the future (also branching/conditions in the code was changed) we can diagnose better.

Closing.

**Closed by simcap** 2017-05-24 13:38 UTC
Labels: bug
