### ISSUE TITLE
AWS profile support

### ISSUE THREAD

**Issue by aneal** [wallix/awless#48] opened 2017-02-17 21:59 UTC
I work with many AWS accounts everyday and exporting my `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` every time I is not plausible.  Adding --profile NAME support would make this tool usable.

**Comment by fxaguessy** [comment] 2017-02-18 08:01
Duplicate of #33. Fixed by 999c979c4559f. It will be in release 0.0.14

**Closed by fxaguessy** 2017-02-18 08:01 UTC
